---
title: "Pie charts depicting proportion of regulatory domains"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 6
    fig_width: 6
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loadings
## Load libraries
```{r}
library(ggplot2)
```

# LSD1 binding sites by emission parameter 
```{r}
Lsd1.midpoint_E1to12 <- c(770, 2060, 451, 564, 8, 117, 10090, 7, 7, 13, 19, 0)

gg.df <- data.frame(
  regions = c(paste("E", 1:12, sep="")),
  midpoint = Lsd1.midpoint_E1to12,
  percentages = Lsd1.midpoint_E1to12/sum(Lsd1.midpoint_E1to12)*100
)

gg.df$regions <- factor(gg.df$regions, c(paste("E", 1:12, sep="")))

pie <- ggplot(gg.df, aes(x="", y=midpoint, fill=regions)) +
  geom_bar(width = 1, stat = "identity") + 
  coord_polar("y", start=0) + 
  theme_classic() + 
  theme(axis.text.x=element_blank())
pie
```

# Binding sites by emission parameter for other factors
```{r}
regions <- c("E1", "E10", "E11", "E12", "E2", "E3", "E4", "E5", "E6", "E7", "E8", "E9")
Brd4 <- c(562, 40, 8, 15, 294, 395, 1166, 94, 74, 6583, 19, 4)
Cdk9 <- c(3301, 49, 41, 11, 1088, 1126, 1935, 35, 278, 8127, 9, 32)
Nelfa <- c(694, 63, 28, 5, 3137, 586, 803, 21, 369, 23023, 76, 6)
Spt5 <- c(760, 1225, 302, 34, 642, 2110, 932, 89, 1422, 12681, 31, 1834)
TBP <- c(187, 30, 10, 2, 517, 122, 201, 7, 72, 7771, 13, 2)
Pol2 <- c(31, 4, 11, 13, 0, 3, 6, 7, 27, 867, 54, 0)
cMyc <- c(63,14,6,6,158,42,183,7,107,4086,1,4)

goi <- list(Brd4, Cdk9, Nelfa, Spt5, TBP, Pol2, cMyc)
names(goi) <- c("Brd4", "Cdk9", "Nelfa", "Spt5", "TBP", "Pol2", "cMyc")
lapply(goi, sum)

for (i in 1:length(goi)) {
  
  factors <- goi[[i]]
  
  names(factors) <- regions
  factors <- factors[paste("E", 1:12, sep="")]
  
  df <- data.frame(
    regions = c(paste("E", 1:12, sep="")),
    midpoint = factors,
    percentages = factors/sum(factors)*100
  )
  
  df$regions <- factor(df$regions, c(paste("E", 1:12, sep="")))

  pie <- ggplot(df, aes(x="", y=midpoint, fill=regions)) +
    geom_bar(width = 1, stat = "identity") + 
    coord_polar("y", start=0) + 
    theme_classic() + 
    ggtitle(names(goi)[[i]],paste("n=",sum(goi[[i]]))) + 
    theme(axis.text.x=element_blank(), legend.position = "bottom")
  
  bar <- ggplot(df, aes(x=regions, y
                        =percentages, 
                        label=round(percentages,1)))+
  geom_col() + 
  geom_text(aes(x=regions, y=percentages),
            size = 3, 
            position = position_stack(vjust = 0.5))
  
  gridExtra::grid.arrange(pie, bar, ncol=2)
}
```

# Session Info
```{r}
sessioninfo::session_info()
```
