---
title: "Density plots depicting the binding of DNA binding factors across regulatory domains"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 3
    fig_width: 6
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loadings
## Load libraries
```{r}
library(readr)
library(ggplot2)
```

## Load tagDensity files of Lsd1 binding sites
```{r}
tagDensity_files <- list.files(path = "../../Data/tagDensity_E1-7/",
                               pattern = "*tagDensity*")
tagDensity_PPPmachinery <- lapply(paste("../../Data/tagDensity_E1-7/", 
                                        tagDensity_files, sep=""), 
                                  read.table)
names(tagDensity_PPPmachinery) <- tagDensity_files
```

# Generate densities for all regions
```{r}
regions <- c("E7", "E6", "E4", "E3", "E2", "E1")
tagDensity.signal <- sapply(strsplit(tagDensity_files[1:11], "_"), "[[", 3)
  
tagDensity_PPPmachinery.list <- list()
for (i in 1:length(regions)){
  tagDensity_PPPmachinery.list[[i]] <-
  tagDensity_PPPmachinery[grepl(regions[[i]], tagDensity_files)]
}
```

```{r}
df.tgDensity <- list()
for (i in 1:length(tagDensity.signal)){
  
  df.tgDensity[[i]] <- data.frame(
    
    position=tagDensity_PPPmachinery.list[[1]][[1]]$V1,
    
    E7 = tagDensity_PPPmachinery.list[[1]][[i]]$V4,
    E6 = tagDensity_PPPmachinery.list[[2]][[i]]$V4,
    E4 = tagDensity_PPPmachinery.list[[3]][[i]]$V4,
    E3 = tagDensity_PPPmachinery.list[[4]][[i]]$V4,
    E2 = tagDensity_PPPmachinery.list[[5]][[i]]$V4,
    E1 = tagDensity_PPPmachinery.list[[6]][[i]]$V4)
  
}
names(df.tgDensity) <- tagDensity.signal
```

```{r}
for (i in 1:length(tagDensity.signal)) {
  
df.tgDensity.long <- reshape2::melt(df.tgDensity[[i]], 
                                    id.vars = "position",
                                    variable.name = "chromHMM", 
                                    value.name = "value")
head(df.tgDensity.long)
df.tgDensity.long$position = as.numeric(df.tgDensity.long$position)
df.tgDensity.long$value = as.numeric(df.tgDensity.long$value)
df.tgDensity.long$chromHMM = as.factor(df.tgDensity.long$chromHMM)

logFunc <- function(x) {
  x.log <- log10(x);
  x.log[is.infinite(x.log)] <- 0
  x.log
}

df.tgDensity.long$value <- logFunc(df.tgDensity.long$value)

gg <- ggplot(df.tgDensity.long, 
       aes(x=position, y=value, col=chromHMM)) + 
  geom_line(size=1) + 
  facet_wrap(~chromHMM, ncol=6) +
  ggtitle(tagDensity.signal[[i]])

print(gg)

}
```

```{r}
curve.fit <- function(y, span=0.15, fit=T) {
   if (fit) {
      x <- 1:length(y)
      y.loess <- loess(y ~ x, span=span, data.frame(x=x, y=y))
      y.predict <- predict(y.loess, data.frame(x=1:length(y)))
	  return (y.predict)
   } else {
      return (y)
   }
}
m <- 1000000


par(mfrow=c(1,6))

E7 <- E6 <- E4 <- E3 <- E2 <- E1 <- list()
a <- b <- list()

for (i in 1:length(tagDensity.signal)) {

	E7[[i]] <- curve.fit(df.tgDensity[[i]][25:75,"E7"], fit=T)*m
	E6[[i]] <- curve.fit(df.tgDensity[[i]][25:75,"E6"], fit=T)*m
	E4[[i]] <- curve.fit(df.tgDensity[[i]][25:75,"E4"], fit=T)*m
	E3[[i]] <- curve.fit(df.tgDensity[[i]][25:75,"E3"], fit=T)*m
	E2[[i]] <- curve.fit(df.tgDensity[[i]][25:75,"E2"], fit=T)*m
	E1[[i]] <- curve.fit(df.tgDensity[[i]][25:75,"E1"], fit=T)*m

	a[[i]] <- min(c(E7[[i]], E6[[i]], E4[[i]], E3[[i]], E2[[i]], E1[[i]]), na.rm=T)
	b[[i]] <- max(c(E7[[i]], E6[[i]], E4[[i]], E3[[i]], E2[[i]], E1[[i]]), na.rm=T)
	margin <- (b[[i]] - a[[i]]) / 20
	a[[i]] <- a[[i]] - margin
	b[[i]] <- b[[i]] + margin
	
}
```

# Generate densities for E7, E4, and E3
```{r}
tgDensity_regions <- list(E7, E4, E3)
names(tgDensity_regions) <- c("E7", "E4", "E3")
col <- c("purple", "red", "blue")

par(mfrow=c(1,3))
for (i in 1:length(tagDensity.signal)) {
  
  for (y in 1:length(tgDensity_regions)) {
    
    plot(tgDensity_regions[[y]][[i]], type="l", lwd=2, 
         ylim=c(a[[i]], b[[i]]),
         col=col[[y]], 
         main=tagDensity.signal[[i]],
         sub=names(tgDensity_regions)[[y]],
         cex.main=1, 
         ylab="rpm/bp", 
         xlab="binding site", 
         xaxt="n")
    axis(1, at=seq(25, 75, by=25), 
         labels=c("TSS", "2.5kb", "0"))
    
  }
}
```

# Session Info
```{r}
sessioninfo::session_info()
```

