---
title: "GSEA analysis"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script performs gene-set enrichment test on the three gene sets.

# Loading 
## Load libraries
```{r}
library(PhosR)
```

## Load target genes
```{r}
load("../../Data/mRNA.RData", verbose = TRUE)
load("../../Data/targets.RData")
```

# Prepare gene sets from DAVID
```{r}
## Enrichment analysis using Gene Ontology Biological Process from DAVID database
# Parse GOBP from DAVID database
GOBP.all <- read.delim("../../Data/OFFICIAL_GENE_SYMBOL2GOTERM_BP_ALL.txt",
                       head=FALSE)
GOBP.all.raw <- split(toupper(as.character(GOBP.all[,1])), sapply(strsplit(as.character(GOBP.all[,2]), "~"), function(x){x[2]}))
GOBP.all.unique <- sapply(GOBP.all.raw, unique)
GOBP.all.list <- sapply(GOBP.all.unique, function(x){x[grep("^LOC", x, invert=TRUE)]})
```

# Perform gene set enrichment analysis
```{r}
ESC_geneUniverse <- toupper(gsub(".+~", "", rownames(mRNA.rlog)))

cMyc.enrich <- pathwayOverrepresent(setdiff(cMyc.targets, 
                                            union(common.targets,Lsd1.targets)),
                                    GOBP.all.list, 
                                    universe = ESC_geneUniverse)
common.enrich <- pathwayOverrepresent(setdiff(common.targets,
                                              union(cMyc.targets,Lsd1.targets)), 
                                      GOBP.all.list, 
                                      universe = ESC_geneUniverse)
Lsd1.enrich <- pathwayOverrepresent(setdiff(Lsd1.targets, 
                                            union(common.targets, cMyc.targets)),
                                    GOBP.all.list, 
                                    universe = ESC_geneUniverse)
```

# Plot GSEA results
```{r}
o <- rownames(cMyc.enrich)[1:100]
idx <- order(-log10(as.numeric(cMyc.enrich[o,1])) - 
               -log10(as.numeric(common.enrich[o,1])), 
             decreasing = TRUE)[1:10]

o <- rownames(common.enrich)[1:100]
idx2 <- order(-log10(as.numeric(common.enrich[o,1])) - 
                -log10(as.numeric(cMyc.enrich[o,1])), 
              decreasing = TRUE)[1:10]

o <- rownames(Lsd1.enrich)[1:100]
idx3 <- order(-log10(as.numeric(Lsd1.enrich[o,1])) - 
                -log10(as.numeric(common.enrich[o,1])), 
              decreasing = TRUE)[1:10]

sel <-c(rownames(cMyc.enrich)[1:100][sort(idx)], 
        rownames(common.enrich)[1:100][sort(idx2)],
        rownames(Lsd1.enrich)[1:100][sort(idx3)])

mat <- rbind(-log10(as.numeric(cMyc.enrich[sel, 1])),
             -log10(as.numeric(common.enrich[sel, 1])),
             -log10(as.numeric(Lsd1.enrich[sel, 1])))
colnames(mat) <- sel

barplot(mat, beside = TRUE, col = c("orange", "purple", "lightblue"), las=2)
```

# Session Info
```{r}
sessioninfo::session_info()
```
