---
title: "Odds ratio plot"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 12
    fig_width: 12
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary
This script performs enrichment test on the three gene sets.

# Loading 
## Load libraries
```{r}
library(epitools)
library(ggplot2)
```

## Target genes
```{r}
load("../../Data/TopGeneSets.RData")
```

## Create geneSet list
```{r}
t =list(myc=combined_cMycSpecific_rank_sorted,
        common=combined_common_rank_sorted,
        lsd1=combined_Lsd1Specific_rank_sorted)

t$common <- t$common[!t$common %in% t$myc]
t$common <- t$common[!t$common %in% t$lsd1]

t$myc <- t$myc[!t$myc %in% t$common]
t$lsd1 <- t$lsd1[!t$lsd1 %in% t$common]

sapply(t, length)
```

## load CR, TF, TC, and SEGs
```{r pressure, echo=FALSE}
# Chromatin remodellers
CR <- read.delim("../../Data/CR_mouse.txt")
CR <- toupper(CR$Symbol)

# Transcription factors
TF <- read.delim("../../Data/TF_mouse.txt")
TF <- toupper(TF$Symbol)

# Transcription co-factors
TC <- read.delim("../../Data/TC_mouse.txt")
TC <- toupper(TC$Symbol)

load("../../Data/SEGs.rda", verbose=T)
```

# OR and Fisher's exact test
CR
```{r include=FALSE}
tabCR <- cbind(table(t$myc %in% CR), 
             table(t$lsd1 %in% CR),
             table(t$common %in% CR))
colnames(tabCR) <- c("myc", "lsd", "common")
tabCR
fisher.test(tabCR)
```

TC
```{r}
tabTC <- cbind(table(t$myc %in% TC), 
             table(t$lsd1 %in% TC),
             table(t$common %in% TC))
colnames(tabTC) <- c("myc", "lsd", "common")
tabTC
fisher.test(tabTC)
```

TF
```{r}
tabTF <- cbind(table(t$myc %in% TF), 
             table(t$lsd1 %in% TF),
             table(t$common %in% TF))
colnames(tabTF) <- c("myc", "lsd", "common")
tabTF
fisher.test(tabTF)
```

SEG
```{r}
tabSEG <- cbind(table(t$myc %in% mSEGs), 
             table(t$lsd1 %in% mSEGs),
             table(t$common %in% mSEGs))
colnames(tabSEG) <- c("myc", "lsd", "common")
tabSEG
fisher.test(tabSEG)
```

# 2x2 contingency table
```{r}
tabTF1 <- cbind(table(t$myc %in% TF), 
             table(t$common %in% TF))
colnames(tabTF1) <- c("myc", "common")
tabTF1
tabTF1 <- tabTF1[,c(2,1)]
fisher.test(tabTF1)

tabTF2 <- cbind(table(t$lsd1 %in% TF), 
             table(t$common %in% TF))
colnames(tabTF2) <- c("lsd1", "common")
tabTF2
tabTF2 <- tabTF2[,c(2,1)]
fisher.test(tabTF2)

tabTF3 <- cbind(table(t$lsd1 %in% TF),
                table(t$myc %in% TF)
             )
colnames(tabTF3) <- c("lsd1","cmyc")
tabTF3
tabTF3 <- tabTF3[,c(2,1)]
fisher.test(tabTF3)
```

```{r}
tabSEG1 <- cbind(table(t$myc %in% mSEGs), 
             table(t$common %in% mSEGs))
colnames(tabSEG1) <- c("myc", "common")
tabSEG1
tabSEG1 <- tabSEG1[,c(2,1)]
fisher.test(tabSEG1)

tabSEG2 <- cbind(table(t$lsd1 %in% mSEGs), 
             table(t$common %in% mSEGs))
colnames(tabSEG2) <- c("lsd1", "common")
tabSEG2
tabSEG2 <- tabSEG2[,c(2,1)]
fisher.test(tabSEG2)

tabSEG3 <- cbind(table(t$lsd1 %in% mSEGs),
                 table(t$myc %in% mSEGs))
colnames(tabSEG3) <- c("lsd1", "cmyc")
tabSEG3
tabSEG3 <- tabSEG3[,c(2,1)]
fisher.test(tabSEG3)
```

# Calculate odds ratio
```{r}
oddsratio.wald(tabTF1)$measure
oddsratio.wald(tabTF1)$p.value
oddsratio.wald(tabTF1)$data

oddsratio.wald(tabTF2)$measure
oddsratio.wald(tabTF2)$p.value
oddsratio.wald(tabTF2)$data

oddsratio.wald(tabTF3)$measure
oddsratio.wald(tabTF3)$p.value
oddsratio.wald(tabTF3)$data

oddsratio.wald(tabSEG1)$measure
oddsratio.wald(tabSEG1)$p.value

oddsratio.wald(tabSEG2)$measure
oddsratio.wald(tabSEG2)$p.value

oddsratio.wald(tabSEG3)$measure
oddsratio.wald(tabSEG3)$p.value
```

# Visualise
```{r}
boxLabels=c("cMyc_vs_Common", "Lsd1_vs_Common", "Lsd1_vs_cMyc")
boxLabels=factor(boxLabels, levels=boxLabels)

df <- data.frame(yAxis = boxLabels,
  boxOdds = 
   c(oddsratio.wald(tabTF1)$measure[2,1],
     oddsratio.wald(tabTF2)$measure[2,1],
     oddsratio.wald(tabTF3)$measure[2,1]),
  boxCILow = 
   c(oddsratio.wald(tabTF1)$measure[2,2],
     oddsratio.wald(tabTF2)$measure[2,2],
     oddsratio.wald(tabTF3)$measure[2,2]),
  boxCIHigh = 
  c(oddsratio.wald(tabTF1)$measure[2,3],
    oddsratio.wald(tabTF2)$measure[2,3],
    oddsratio.wald(tabTF3)$measure[2,3])
)

p1 <- ggplot(df, aes(x = boxOdds, y = boxLabels)) +
    geom_vline(aes(xintercept = 1), size = .25, linetype = 'dashed') +
    geom_errorbarh(aes(xmax = boxCIHigh, xmin = boxCILow), size = .5, height = 
                       .2, color = 'gray50') +
    geom_point(size = 3.5, color = 'orange') +
    theme_bw() +
    theme(panel.grid.minor = element_blank()) +
    scale_x_continuous(breaks = seq(0,7,1) ) +
    coord_trans(x = 'log10') +
    ylab('') +
    xlab('Odds ratio (log scale)') +
    ggtitle('TF enrichment')

df <- data.frame(yAxis = boxLabels,
  boxOdds = 
   c(oddsratio.wald(tabSEG1)$measure[2,1],
     oddsratio.wald(tabSEG2)$measure[2,1],
     oddsratio.wald(tabSEG3)$measure[2,1]),
  boxCILow = 
   c(oddsratio.wald(tabSEG1)$measure[2,2],
     oddsratio.wald(tabSEG2)$measure[2,2],
     oddsratio.wald(tabSEG3)$measure[2,2]),
  boxCIHigh = 
  c(oddsratio.wald(tabSEG1)$measure[2,3],
    oddsratio.wald(tabSEG2)$measure[2,3],
    oddsratio.wald(tabSEG3)$measure[2,3])
)

p2 <- ggplot(df, aes(x = boxOdds, y = boxLabels)) +
    geom_vline(aes(xintercept = 1), size = .25, linetype = 'dashed') +
    geom_errorbarh(aes(xmax = boxCIHigh, xmin = boxCILow), size = .5, height = 
                       .2, color = 'gray50') +
    geom_point(size = 3.5, color = 'orange') +
    theme_bw() +
    theme(panel.grid.minor = element_blank()) +
    scale_x_continuous(breaks = seq(0,7,1) ) +
    coord_trans(x = 'log10') +
    ylab('') +
    xlab('Odds ratio (log scale)') +
    ggtitle('SEG enrichment')


ggpubr::ggarrange(p1,p2, ncol=1)
```

# Combine plots

```{r}
boxLabels=c("TF_cMyc_vs_Common", 
            "TF_Lsd1_vs_Common", 
            "TF_Lsd1_vs_cMyc",
            "SEG_cMyc_vs_Common",
            "SEG_Lsd1_vs_Common", 
            "SEG_Lsd1_vs_cMyc")
boxLabels=factor(boxLabels, levels=boxLabels)

df <- data.frame(yAxis = boxLabels,
  boxOdds = 
   c(oddsratio.wald(tabTF1)$measure[2,1],
     oddsratio.wald(tabTF2)$measure[2,1],
     oddsratio.wald(tabTF3)$measure[2,1],
     oddsratio.wald(tabSEG1)$measure[2,1],
     oddsratio.wald(tabSEG2)$measure[2,1],
     oddsratio.wald(tabSEG3)$measure[2,1]),
  boxCILow = 
   c(oddsratio.wald(tabTF1)$measure[2,2],
     oddsratio.wald(tabTF2)$measure[2,2],
     oddsratio.wald(tabTF3)$measure[2,2],
     oddsratio.wald(tabSEG1)$measure[2,2],
     oddsratio.wald(tabSEG2)$measure[2,2],
     oddsratio.wald(tabSEG3)$measure[2,2]),
  boxCIHigh = 
  c(oddsratio.wald(tabTF1)$measure[2,3],
    oddsratio.wald(tabTF2)$measure[2,3],
    oddsratio.wald(tabTF3)$measure[2,3],
    oddsratio.wald(tabSEG1)$measure[2,3],
    oddsratio.wald(tabSEG2)$measure[2,3],
    oddsratio.wald(tabSEG3)$measure[2,3])
)

ggplot(df, aes(x = boxOdds, y = boxLabels)) +
    geom_vline(aes(xintercept = 1), size = .25, linetype = 'dashed') +
    geom_errorbarh(aes(xmax = boxCIHigh, xmin = boxCILow), size = .5, height = 
                       .2, color = 'gray50') +
    geom_point(size = 3.5, color = 'orange') +
    theme_bw() +
    theme(panel.grid.minor = element_blank()) +
    scale_x_continuous(breaks = seq(0,7,1) ) +
    coord_trans(x = 'log10') +
    ylab('') +
    xlab('Odds ratio (log scale)') +
    ggtitle('Enrichment')
```

# Session Info
```{r}
sessioninfo::session_info()
```
