---
title: "Density plots for LSD1-specific, cMyc-specific, and common sites"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 6
    fig_width: 6
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loadings
## Load libraries
```{r}
library(readr)
```

# Create tagDensity files of cMyc-specific, Lsd1-specific, Lsd1-cMyc-common sites
## Histone marks and other factors
```{r}
tagDensity_files <- list.files(path = "../../Data/TagDensity_AllSites_E7/",
                               pattern="*tagDensity*")

factors <- c("H3K27ac_0h", 
             "H3K27me3_0h", 
             "H3K4me3_0h",
             "H3K4me2_r2", 
             "H3K9me2_r2", 
             "H3K9ac_r1")

par(mfrow=c(2,3))

for(i in 1:length(factors)) {
  
  c1 <- read.delim(paste("../../Data/TagDensity_AllSites_E7/cMyc-specific.tagDensity.format_",
                         factors[i], sep=""), header = F)
  c2 <- read.delim(paste("../../Data/TagDensity_AllSites_E7/Lsd1-cMyc-common.tagDensity.format_",
                         factors[i], sep=""), header = F)
  c3 <- read.delim(paste("../../Data/TagDensity_AllSites_E7/Lsd1-specific.tagDensity.format_",
                         factors[i], sep=""), header = F)
  
  ## curve based fitting
  curve.fit <- function(y, span=0.2, fit=T) {
    if (fit) {
      x <- 1:length(y)
      y.loess <- loess(y ~ x, span=span, data.frame(x=x, y=y))
      y.predict <- predict(y.loess, data.frame(x=1:length(y)))
      return (y.predict)
    } else {
      return (y)
    }
  }
  m <- 1000000

  all_1sig <- curve.fit(c1[25:75,'V4'], fit=T)*m
  all_2sig <- curve.fit(c2[25:75,'V4'], fit=T)*m
  all_3sig <- curve.fit(c3[25:75,'V4'], fit=T)*m
  
  a <- min(c(all_1sig, all_2sig, all_3sig), na.rm=T)
  b <- max(c(all_1sig, all_2sig, all_3sig), na.rm=T)
  margin <- (b - a) / 20
  a <- a - margin
  b <- b + margin
  
  plot(all_1sig, type="l", lwd=2, 
       ylim=c(a, b),
       col="red", #cMyc-specific
       main=factors[[i]],
       cex.main=1, 
       ylab="rpm/bp", 
       xaxt="n")
  axis(1, at=seq(25, 75, by=25), 
       labels=c("TSS", "2.5kb", "0"))
  points(all_2sig, type="l", lwd=2, 
         ylim=c(a, b),
         col="skyblue", #common
         cex.main=1)
  points(all_3sig, type="l", lwd=2, 
         ylim=c(a, b),
         col="green", #Lsd1-specific
         cex.main=1)
}
```

## DNAseI
```{r}
tagDensity_files <- list.files(path = "../../Data/tagDensity_DNaseI",
                                pattern="*tagDensity*")

factors <- gsub("cMyc-specific.tagDensity.format_", "", tagDensity_files[grep("cMyc-specific.tagDensity.format_", tagDensity_files)])[[1]]

par(mfrow=c(1,1))

for(i in 1:length(factors)) {

  c1 <- read.delim(paste("../../Data/tagDensity_DNaseI/cMyc-specific.tagDensity.format_", 
                         factors[i], sep=""), header = F)
  c2 <- read.delim(paste("../../Data/tagDensity_DNaseI/Lsd1-cMyc-common.tagDensity.format_", 
                         factors[i], sep=""), header = F)
  c3 <- read.delim(paste("../../Data/tagDensity_DNaseI/Lsd1-specific.tagDensity.format_", 
                         factors[i], sep=""), header = F)
  
  ## curve based fitting
  curve.fit <- function(y, span=0.5, fit=T) {
    if (fit) {
      x <- 1:length(y)
      y.loess <- loess(y ~ x, span=span, data.frame(x=x, y=y))
      y.predict <- predict(y.loess, data.frame(x=1:length(y)))
      return (y.predict)
    } else {
      return (y)
    }
  }
  m <- 1000000
  
  all_1sig <- curve.fit(c1[25:75,'V4'], fit=T)*m
  all_2sig <- curve.fit(c2[25:75,'V4'], fit=T)*m
  all_3sig <- curve.fit(c3[25:75,'V4'], fit=T)*m
  
  a <- min(c(all_1sig, all_2sig, all_3sig), na.rm=T)
  b <- max(c(all_1sig, all_2sig, all_3sig), na.rm=T)
  margin <- (b - a) / 20
  a <- a - margin
  b <- b + margin
  
  plot(all_1sig, type="l", lwd=2, 
       ylim=c(a, b),
       col="red", #cMyc-specific
       main=factors[[i]],
       cex.main=1, 
       ylab="rpm/bp", 
       xaxt="n")
  axis(1, at=seq(25, 75, by=25), 
       labels=c("TSS", "2.5kb", "0"))
  points(all_2sig, type="l", lwd=2, 
         ylim=c(a, b),
         col="skyblue", #common
         cex.main=1)
  points(all_3sig, type="l", lwd=2, 
         ylim=c(a, b),
         col="green", #Lsd1-specific
         cex.main=1)
}
```

## cMyc
```{r}
tagDensity_files4 <- list.files(path = "../../Data/tagDensity_cMycversion",
                                pattern="*tagDensity*")

factors <- "cMyc"

par(mfrow=c(1,1))

for(i in 1:length(factors)) {

  c3 <- read.delim("../../Data/tagDensity_cMycversion/cMyc2-specific2Lsd1.tagDensity_cMyc", 
                   header = F) # Lsd1
  c2 <- read.delim("../../Data/tagDensity_cMycversion/Lsd1-cMyc-common2.tagDensity_cMyc", 
                   header = F) # common
  c1 <- read.delim("../../Data/tagDensity_cMycversion/Lsd1-specific2Lsd1.tagDensity_cMyc", 
                   header = F) # cMyc
  
  ## curve based fitting
  curve.fit <- function(y, span=0.2, fit=T) {
    if (fit) {
      x <- 1:length(y)
      y.loess <- loess(y ~ x, span=span, data.frame(x=x, y=y))
      y.predict <- predict(y.loess, data.frame(x=1:length(y)))
      return (y.predict)
    } else {
      return (y)
    }
  }
  m <- 1000000
  
  
  all_1sig <- curve.fit(c1[25:75,'V4'], fit=T)*m
  all_2sig <- curve.fit(c2[25:75,'V4'], fit=T)*m
  all_3sig <- curve.fit(c3[25:75,'V4'], fit=T)*m
  
  a <- min(c(all_1sig, all_2sig, all_3sig), na.rm=T)
  b <- max(c(all_1sig, all_2sig, all_3sig), na.rm=T)
  margin <- (b - a) / 20
  a <- a - margin
  b <- b + margin
  
  plot(all_1sig, type="l", lwd=2, 
       ylim=c(a, b),
       col="red", #cMyc-specific
       main=factors[[i]],
       cex.main=1, 
       ylab="rpm/bp", 
       xaxt="n")
  axis(1, at=seq(25, 75, by=25), 
       labels=c("TSS", "2.5kb", "0"))
  points(all_2sig, type="l", lwd=2, 
         ylim=c(a, b),
         col="skyblue", #common
         cex.main=1)
  points(all_3sig, type="l", lwd=2, 
         ylim=c(a, b),
         col="green", #Lsd1-specific
         cex.main=1)
}
```

## Brd4
```{r}
tagDensity_files <- list.files(path = "../../Data/Boxplot_tgDensity_Brd4",
                               pattern="*tagDensity*")

factors <- gsub("cMyc-specific.tagDensity.format_", "", tagDensity_files[grep("cMyc-specific.tagDensity.format_", tagDensity_files)])

par(mfrow=c(1,1))

for(i in 1:length(factors)) {

  c1 <- read.delim(paste("../../Data/Boxplot_tgDensity_Brd4/cMyc-specific.tagDensity.format_",
                         factors[i], sep=""), header = F)
  c2 <- read.delim(paste("../../Data/Boxplot_tgDensity_Brd4/Lsd1-cMyc-common.tagDensity.format_",
                         factors[i], sep=""), header = F)
  c3 <- read.delim(paste("../../Data/Boxplot_tgDensity_Brd4/Lsd1-specific.tagDensity.format_",
                         factors[i], sep=""), header = F)
  
  ## curve based fitting
  curve.fit <- function(y, span=0.2, fit=T) {
    if (fit) {
      x <- 1:length(y)
      y.loess <- loess(y ~ x, span=span, data.frame(x=x, y=y))
      y.predict <- predict(y.loess, data.frame(x=1:length(y)))
      return (y.predict)
    } else {
      return (y)
    }
  }
  m <- 1000000
  
  
  all_1sig <- curve.fit(c1[25:75,'V4'], fit=T)*m
  all_2sig <- curve.fit(c2[25:75,'V4'], fit=T)*m
  all_3sig <- curve.fit(c3[25:75,'V4'], fit=T)*m
  
  a <- min(c(all_1sig, all_2sig, all_3sig), na.rm=T)
  b <- max(c(all_1sig, all_2sig, all_3sig), na.rm=T)
  margin <- (b - a) / 20
  a <- a - margin
  b <- b + margin
  
  plot(all_1sig, type="l", lwd=2, 
       ylim=c(a, b),
       col="red", #cMyc-specific
       main=factors[[i]],
       cex.main=1, 
       ylab="rpm/bp", 
       xaxt="n")
  axis(1, at=seq(25, 75, by=25), 
       labels=c("TSS", "2.5kb", "0"))
  points(all_2sig, type="l", lwd=2, 
         ylim=c(a, b),
         col="skyblue", #common
         cex.main=1)
  points(all_3sig, type="l", lwd=2, 
         ylim=c(a, b),
         col="green", #Lsd1-specific
         cex.main=1)
}

```

# Session Info
```{r}
sessioninfo::session_info()
```
