---
title: "Boxplots for LSD1-specific, cMyc-specific, and common sites"
author: "Hani Kim"
date: "`r paste0('Initiated on 2020 Oct 31, compiled on ', format(Sys.time(), '%Y %b %d'))`"
output:
  html_document:
    code_folding: hide
    fig_height: 6
    fig_width: 6
    toc: yes
    number_sections: true
    toc_depth: 3
    toc_float: yes
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loadings
## Load libraries
```{r}
library(readr)
```

# Create boxplots of cMyc-specific, Lsd1-specific, Lsd1-cMyc-common sites

## All factors
```{r}
files <- list.files("../../Data/Boxplot_AllSites/")
factors <- gsub("cMyc-specific.boxplot.format_", "", 
                files[grep("cMyc-specific.boxplot.format_", files)])

path = "../../Data/Boxplot_AllSites/"

par(mfrow=c(2,3))
for(i in 1:length(factors)) {
  
  c1 <- read.delim(paste(path, "cMyc-specific.boxplot.format_", factors[i], sep=""), header = F)
  c2 <- read.delim(paste(path, "Lsd1-specific.boxplot.format_", factors[i], sep=""), header = F)
  c3 <- read.delim(paste(path, "Lsd1-cMyc-common.boxplot.format_", factors[i], sep=""), header = F)
  
  boxplot(log2(c1[,7]), 
          log2(c3[,7]), 
          log2(c2[,7]), 
          main=factors[i], 
          notch = TRUE, 
          col = c("red", "green3", "blue"), 
          outline = F)
}
```

## BRD4
```{r}
boxplot_files <- list.files(path = "../../Data/Boxplot_tgDensity_Brd4",
                            pattern = "*boxplot*")

factors <- gsub("cMyc-specific.boxplot.format_", "",
                boxplot_files[grep("cMyc-specific.boxplot.format_", boxplot_files)])

par(mfrow=c(1,1))

for(i in 1:length(factors)) {

  c1 <- read.delim(paste("../../Data/Boxplot_tgDensity_Brd4/cMyc-specific.boxplot.format_", 
                         factors[i], sep=""), header = F)
  c2 <- read.delim(paste("../../Data/Boxplot_tgDensity_Brd4/Lsd1-cMyc-common.boxplot.format_",
                         factors[i], sep=""), header = F)
  c3 <- read.delim(paste("../../Data/Boxplot_tgDensity_Brd4/Lsd1-specific.boxplot.format_", 
                         factors[i], sep=""), header = F)
  
  boxplot(log2(c1$V7), log2(c2$V7), log2(c3$V7),
          notch=T,
          outline=F,
       col=c("red","skyblue", "green"),
       main=factors[[i]],
       ylab="rpm/bp", 
       xaxt="n")
}
```

# Wilcoxon-Mann-Whitney test
```{r}
files <- list.files("../../Data/Boxplot_AllSites/")
factors <- gsub("cMyc-specific.boxplot.format_", "", 
                files[grep("cMyc-specific.boxplot.format_", files)])

path = "../../Data/Boxplot_AllSites/"

for(i in 1:length(factors)) {
  
  c1 <- read.delim(paste(path, "cMyc-specific.boxplot.format_", factors[i], sep=""), header = F)
  c3 <- read.delim(paste(path, "Lsd1-specific.boxplot.format_", factors[i], sep=""), header = F)
  c2 <- read.delim(paste(path, "Lsd1-cMyc-common.boxplot.format_", factors[i], sep=""), header = F)
  
  print(factors[[i]])
  print(wilcox.test(log2(c1[,7]), log2(c2[,7]),
                    alternative = c("two.sided"),
                    mu = 0, paired = FALSE, exact = NULL, correct = TRUE,
                    conf.int = FALSE, conf.level = 0.95))
  print(wilcox.test(log2(c2[,7]), log2(c3[,7]),
                    alternative = c("two.sided"),
                    mu = 0, paired = FALSE, exact = NULL, correct = TRUE,
                    conf.int = FALSE, conf.level = 0.95))
  print(wilcox.test(log2(c1[,7]), log2(c3[,7]),
                    alternative = c("two.sided"),
                    mu = 0, paired = FALSE, exact = NULL, correct = TRUE,
                    conf.int = FALSE, conf.level = 0.95))
}
```

# Session Info
```{r}
sessioninfo::session_info()
```
